name: Latest Publications Cronjob

on:
  schedule:
    - cron: '26 3 1 * *' # At 3.26am on the 1st of every month
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cronjoblatestpublications:
    name: Latest Publications Cronjob
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Latest Publications Cronjob
        id: run-latest-publications-cronjob
        uses: ./
        with:
          download-limit: '30'
          num-publications: '20'
          randomise: 'false'
          max-collabs: '10'
          commit: 'true'
          'commit-repo': 'NationalGenomicsInfrastructure/ngisweden.se-publications'
          'commit-token': ${{ secrets.TOKEN_FOR_PUBLICATION_COMMITS }}
          'commit-message': 'Update NGI`s latest collaborative publications'
          'json-path': 'cache/latest-publications.json'
